version: 2
updates:
    - package-ecosystem: gradle
      directory: "/"
      schedule:
          interval: daily
      target-branch: "chore/dependabot"
      labels: ["dependabot"]
      open-pull-requests-limit: 10
      ignore:
        - dependency-name: "com.mparticle:android-core"
      commit-message:
        prefix: "chore"
